# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Correlation
#' 
#' Calculates the correlation between two vectors.
#' 
#' @param A First matrix.
#' @param B Second matrix.
#' @param cor Return correlation matrix?
#' @return Numeric matrix. 
cov <- function(A, B, cor = FALSE) {
    .Call('_MGMM_cov', PACKAGE = 'MGMM', A, B, cor)
}

#' Matrix Determinant
#'
#' Calculates the determinant of \eqn{A}.
#'
#' @param A Numeric matrix.
#' @return Scalar. 
det <- function(A) {
    .Call('_MGMM_det', PACKAGE = 'MGMM', A)
}

#' Matrix Inner Product
#'
#' Calculates the product \eqn{A'B}.
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @return Numeric matrix. 
matIP <- function(A, B) {
    .Call('_MGMM_matIP', PACKAGE = 'MGMM', A, B)
}

#' Matrix Inverse
#' 
#' Calcualtes \eqn{A^{-1}}.
#'
#' @param A Numeric matrix.
#' @return Numeric matrix. 
matInv <- function(A) {
    .Call('_MGMM_matInv', PACKAGE = 'MGMM', A)
}

#' Matrix Matrix Product
#'
#' Calculates the product \eqn{AB}. 
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @return Numeric matrix. 
MMP <- function(A, B) {
    .Call('_MGMM_MMP', PACKAGE = 'MGMM', A, B)
}

#' Fast Outer Product
#' 
#' Calculates the outer product \eqn{XY'}.
#' 
#' @param X Numeric matrix.
#' @param Y Numeric matrix.
#' @return Numeric matrix.
matOP <- function(X, Y) {
    .Call('_MGMM_matOP', PACKAGE = 'MGMM', X, Y)
}

#' Schur complement
#'
#' Calculates the efficient information \eqn{I_{bb}-I_{ba}I_{aa}^{-1}I_{ab}}. 
#'
#' @param Ibb Information of target parameter
#' @param Iaa Information of nuisance parameter
#' @param Iba Cross information between target and nuisance parameters
#' @return Numeric matrix. 
SchurC <- function(Ibb, Iaa, Iba) {
    .Call('_MGMM_SchurC', PACKAGE = 'MGMM', Ibb, Iaa, Iba)
}

#' Matrix Trace
#'
#' Calculates the trace of a matrix \eqn{A}.
#'
#' @param A Numeric matrix.
#' @return Scalar.
tr <- function(A) {
    .Call('_MGMM_tr', PACKAGE = 'MGMM', A)
}

